import "reflect-metadata";
import { container } from "tsyringe";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClientToken, JwtServiceToken } from "./di/tokens";
import { JwtService } from "./lib/jwt";
import { EmailService } from "./services/email";
import { AuthService } from "./modules/auth/auth.service";
import { AuthController } from "./modules/auth/auth.controller";
import { ClientQuestionsService } from "./modules/client-questions/client-questions.service";
import { ClientQuestionsController } from "./modules/client-questions/client-questions.controller";
import { CoachAssignmentService } from "./modules/coach-assignment/coach-assignment.service";
import { CoachAssignmentController } from "./modules/coach-assignment/coach-assignment.controller";
import { WorkoutService } from "./modules/workout/workout.service";
import { WorkoutController } from "./modules/workout/workout.controller";
import { WorkoutTemplateService } from "./modules/workout/workout-template.service";
import { WorkoutPlanService } from "./modules/workout/workout-plan.service";
import { WorkoutClientService } from "./modules/workout/workout-client.service";
import { NutritionTemplateService } from "./modules/nutrition/nutrition-template.service";
import { FoodService } from "./modules/nutrition/food.service";
import { NutritionPlanService } from "./modules/nutrition/nutrition-plan.service";
import { NutritionClientService } from "./modules/nutrition/nutrition-client.service";
import { NutritionController } from "./modules/nutrition/nutrition.controller";
import { ProfileService } from "./modules/profile/profile.service";
import { ProfileController } from "./modules/profile/profile.controller";
import { CheckInService } from "./modules/checkin/checkin.service";
import { CheckInController } from "./modules/checkin/checkin.controller";
import { MessagingService } from "./modules/messaging/messaging.service";
import { MessagingController } from "./modules/messaging/messaging.controller";
import { RealtimeService } from "./modules/realtime/realtime.service";
import { RealtimeController } from "./modules/realtime/realtime.controller";
import { OutboxService } from "./events/outbox.service";
import { CoachAchievementsService } from "./modules/coach-achievements/coach-achievements.service";
import { CoachAchievementsController } from "./modules/coach-achievements/coach-achievements.controller";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

container.registerInstance(PrismaClientToken, prisma);
container.registerSingleton(JwtServiceToken, JwtService);
container.registerSingleton(EmailService);
container.registerSingleton(AuthService);
container.registerSingleton(AuthController);
container.registerSingleton(ClientQuestionsService);
container.registerSingleton(ClientQuestionsController);
container.registerSingleton(CoachAssignmentService);
container.registerSingleton(CoachAssignmentController);
container.registerSingleton(WorkoutService);
container.registerSingleton(WorkoutController);
container.registerSingleton(WorkoutTemplateService);
container.registerSingleton(WorkoutPlanService);
container.registerSingleton(WorkoutClientService);
container.registerSingleton(NutritionTemplateService);
container.registerSingleton(FoodService);
container.registerSingleton(NutritionPlanService);
container.registerSingleton(NutritionClientService);
container.registerSingleton(NutritionController);
container.registerSingleton(ProfileService);
container.registerSingleton(ProfileController);
container.registerSingleton(CheckInService);
container.registerSingleton(CheckInController);
container.registerSingleton(MessagingService);
container.registerSingleton(MessagingController);
container.registerSingleton(RealtimeService);
container.registerSingleton(RealtimeController);
container.registerSingleton(OutboxService);
container.registerSingleton(CoachAchievementsService);
container.registerSingleton(CoachAchievementsController);

export { container };
